export default {
    themeBgColor:'bg-[#FF6262]',
    bgColor:'bg-[#EEF0F2]',
    bgWhite:'bg-white',
    shadowLg:'shadow-lg',
    roundedMd:'rounded-lg',
    textPrimary:'text-black',
    textTheme:'text-[#FF6262]',
    textSecondry:'text-gray-600',
    bgSecondry:'bg-gray-600',
    textXs:'text-[11px]',
    textSm:'text-[13px]',
    textMd:'text-[15px]',
    textLg:'text-[21px]',
    textXl:'text-[25px]',
    maxWidth:'max-w-5xl mx-auto',
    padding:'px-3 xl:px-0',
    minHeight:'min-h-[100vh]',
    height:'h-[100%]',
    loginCard: 'bg-white w-[90%] md:w-[80%] lg:w-[50%] 2xl:w-[40%] mx-auto rounded-md shadow-lg grid grid-cols-1 md:grid-cols-2 overflow-hidden',
    inputFeildLg:'border-[1px] border-gray-400 rounded-md w-full text-black font-bold text-[13px] outline-none px-2',
    loginBtn:'text-white bg-[#FF6262] rounded-md w-full text-[15px] font-bold hover:bg-red-400 hover:shadow-lg',
}